export type Vertical = 'arts-music' | 'sports-leisure' | 'fashion-culture' | 'business-news';

export interface Story {
  id: string;
  title: string;
  excerpt: string;
  content: string;
  vertical: Vertical;
  author: string;
  date: string;
  imageUrl: string;
  tags: string[];
  aiGenerated: boolean;
  source: 'ai' | 'manual'; // Track if AI-generated or manually written
  keepIndefinitely?: boolean; // For manual stories that should never be deleted
  lastEdited?: string;
  youtubeUrl?: string; // Optional YouTube embed URL
  sources?: Array<{ title: string; url: string }>; // Real news sources with URLs
}

export interface AgentConfig {
  enabled: boolean;
  autoGenerateDaily: boolean;
  generationTime: string; // HH:MM format
  storiesPerDay: number;
  verticalPrompts: {
    [key in Vertical]: string;
  };
  lastGeneration?: string;
  nextGeneration?: string;
}

export interface GenerationRequest {
  vertical: Vertical;
  customPrompt?: string;
  count: number;
}