import { useState, useEffect } from 'react';
import { Header } from './components/Header';
import { TrendingCarousel } from './components/TrendingCarousel';
import { StoryGrid } from './components/StoryGrid';
import { StoryDetail } from './components/StoryDetail';
import { EditorPanel } from './components/EditorPanel';
import { AIAgentPanel } from './components/AIAgentPanel';
import { ManualStoryForm } from './components/ManualStoryForm';
import { ScheduleSettings } from './components/ScheduleSettings';
import { Footer } from './components/Footer';
import { FakeAd } from './components/FakeAd';
import { AdminLogin } from './components/AdminLogin';
import { mockStories } from './data/mockStories';
import { generateStories } from './utils/aiGenerator';
import type { Story, Vertical, AgentConfig } from './types';
import { toast } from 'sonner';
import { projectId, publicAnonKey } from './utils/supabase/info';

const defaultAgentConfig: AgentConfig = {
  enabled: true,
  autoGenerateDaily: true,
  generationTime: '09:00',
  storiesPerDay: 2,
  verticalPrompts: {
    'arts-music': 'Find trending stories about musicians, artists, concerts, album releases, viral performances, and entertainment industry news',
    'fashion-culture': 'Discover fashion week updates, designer launches, celebrity style, cultural movements, and influential trends',
    'sports-leisure': 'Cover athlete achievements, sports events, fitness trends, esports, and leisure activities gaining popularity',
    'business-news': 'Report on entrepreneur ventures, tech startups, creator economy, business deals, and financial news affecting influencers',
  },
  lastGeneration: new Date().toISOString(),
  nextGeneration: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
};

export default function App() {
  const [selectedVertical, setSelectedVertical] = useState<Vertical | 'all'>('all');
  const [selectedStory, setSelectedStory] = useState<Story | null>(null);
  const [showEditor, setShowEditor] = useState(false);
  const [showAgent, setShowAgent] = useState(false);
  const [showManualForm, setShowManualForm] = useState(false);
  const [showSchedule, setShowSchedule] = useState(false);
  const [stories, setStories] = useState<Story[]>(mockStories);
  const [agentConfig, setAgentConfig] = useState<AgentConfig>(defaultAgentConfig);
  const [isGenerating, setIsGenerating] = useState(false);
  
  // Admin authentication state
  const [isAdmin, setIsAdmin] = useState(false);
  const [showAdminLogin, setShowAdminLogin] = useState(false);
  const [accessToken, setAccessToken] = useState<string | null>(null);

  // Check for admin mode via URL parameter or existing session
  useEffect(() => {
    const checkAdminAccess = async () => {
      const params = new URLSearchParams(window.location.search);
      
      // Check if ?admin=true in URL
      if (params.get('admin') === 'true') {
        // Check if already logged in
        const { createClient } = await import('@supabase/supabase-js');
        const supabase = createClient(
          `https://${projectId}.supabase.co`,
          publicAnonKey
        );

        const { data } = await supabase.auth.getSession();
        
        if (data.session?.access_token) {
          // Already logged in
          setAccessToken(data.session.access_token);
          setIsAdmin(true);
          toast.success('🔐 Admin mode activated');
        } else {
          // Show login
          setShowAdminLogin(true);
        }
      }
    };

    checkAdminAccess();
  }, []);

  const handleAdminLoginSuccess = (token: string) => {
    setAccessToken(token);
    setIsAdmin(true);
    setShowAdminLogin(false);
    toast.success('🔐 Welcome back, admin!');
  };

  const handleAdminLogout = async () => {
    const { createClient } = await import('@supabase/supabase-js');
    const supabase = createClient(
      `https://${projectId}.supabase.co`,
      publicAnonKey
    );
    
    await supabase.auth.signOut();
    setAccessToken(null);
    setIsAdmin(false);
    toast.info('👋 Logged out of admin mode');
  };

  // Auto-cleanup old stories
  const cleanupOldStories = () => {
    const now = new Date();
    let deletedCount = 0;
    
    setStories(prev => {
      const filtered = prev.filter(story => {
        const storyDate = new Date(story.date);
        const ageInDays = (now.getTime() - storyDate.getTime()) / (1000 * 60 * 60 * 24);
        
        // AI stories: delete after 90 days
        if (story.source === 'ai' && ageInDays > 90) {
          deletedCount++;
          return false;
        }
        
        // Manual stories with "keep forever" flag: never delete
        if (story.source === 'manual' && story.keepIndefinitely) {
          return true;
        }
        
        // Manual stories: archive after 1 year
        if (story.source === 'manual' && ageInDays > 365) {
          deletedCount++;
          return false;
        }
        
        return true;
      });
      
      if (deletedCount > 0) {
        toast.info(`🗑️ Cleaned up ${deletedCount} old ${deletedCount === 1 ? 'story' : 'stories'}`);
      }
      
      return filtered;
    });
  };

  // Run cleanup daily at midnight
  useEffect(() => {
    const checkCleanup = setInterval(() => {
      const now = new Date();
      if (now.getHours() === 0 && now.getMinutes() === 0) {
        cleanupOldStories();
      }
    }, 60000); // Check every minute
    
    return () => clearInterval(checkCleanup);
  }, []);

  const filteredStories = selectedVertical === 'all' 
    ? stories 
    : stories.filter(story => story.vertical === selectedVertical);

  // Get top story from each vertical for trending carousel (only when viewing 'all')
  const trendingStories = selectedVertical === 'all' 
    ? (['arts-music', 'fashion-culture', 'sports-leisure', 'business-news'] as Vertical[])
        .map(vertical => stories.find(story => story.vertical === vertical))
        .filter((story): story is Story => story !== undefined)
    : [];

  // Latest stories grid shows all filtered stories chronologically
  const latestStories = filteredStories;

  const handleStoryUpdate = (updatedStory: Story) => {
    setStories(prev => prev.map(s => s.id === updatedStory.id ? updatedStory : s));
    setSelectedStory(updatedStory);
  };

  const handleSaveManualStory = async (story: Partial<Story>) => {
    try {
      const response = await fetch(
        `https://${projectId}.supabase.co/functions/v1/make-server-d2c193b9/save-manual-story`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${publicAnonKey}`,
          },
          body: JSON.stringify(story),
        }
      );

      if (!response.ok) {
        throw new Error('Failed to save story');
      }

      const savedStory: Story = await response.json();
      setStories(prev => [savedStory, ...prev]);
      setShowManualForm(false);
      toast.success('✍️ Manual story published successfully!');
    } catch (error) {
      console.error('Error saving manual story:', error);
      toast.error('Failed to save story. Please try again.');
    }
  };

  const handleGenerateStories = async (vertical: Vertical, count: number, customPrompt?: string, useMockMode?: boolean) => {
    setIsGenerating(true);
    try {
      console.log(`handleGenerateStories called with useMockMode: ${useMockMode}`);
      const newStories = await generateStories(vertical, count, customPrompt, useMockMode);
      setStories(prev => [...newStories, ...prev]);
      setAgentConfig(prev => ({
        ...prev,
        lastGeneration: new Date().toISOString(),
      }));
      
      const modeLabel = useMockMode ? '🎭 MOCK MODE' : '🤖 REAL AI';
      toast.success(`${modeLabel}: Generated ${newStories.length} ${newStories.length === 1 ? 'story' : 'stories'}!`);
    } catch (error) {
      console.error('Error generating stories:', error);
      toast.error('Failed to generate stories. Check console for details.');
    } finally {
      setIsGenerating(false);
    }
  };

  // GO LIVE FEATURE - Generate 12 stories and delete mock data
  const handleGoLive = async () => {
    const confirmed = confirm(
      '🚀 GO LIVE\n\n' +
      'This will:\n' +
      '✅ Generate 12 fresh stories (3 per vertical)\n' +
      '❌ Delete all mock/demo stories\n' +
      '💰 Use real OpenAI API (costs ~$0.10)\n\n' +
      'Continue?'
    );

    if (!confirmed) return;

    setIsGenerating(true);
    toast.info('🚀 Going live! Generating 12 fresh stories...');

    try {
      const verticals: Vertical[] = ['arts-music', 'fashion-culture', 'sports-leisure', 'business-news'];
      const allNewStories: Story[] = [];

      // Generate 3 stories for each vertical
      for (const vertical of verticals) {
        const newStories = await generateStories(vertical, 3, undefined, false); // FALSE = Real AI
        allNewStories.push(...newStories);
        toast.success(`✅ Generated 3 ${vertical} stories`);
        await new Promise(resolve => setTimeout(resolve, 1000)); // Delay to show progress
      }

      // Delete all mock stories and keep only new ones
      setStories(allNewStories);
      setSelectedVertical('all');
      setSelectedStory(null);
      
      toast.success(`🎉 LIVE! Published ${allNewStories.length} fresh stories!`);
    } catch (error) {
      console.error('Error going live:', error);
      toast.error('Failed to go live. Check console for details.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleUpdateConfig = (config: AgentConfig) => {
    setAgentConfig(config);
    
    // Calculate next generation time
    if (config.autoGenerateDaily && config.enabled) {
      const [hours, minutes] = config.generationTime.split(':');
      const nextGen = new Date();
      nextGen.setHours(parseInt(hours), parseInt(minutes), 0, 0);
      
      // If time has passed today, set for tomorrow
      if (nextGen < new Date()) {
        nextGen.setDate(nextGen.getDate() + 1);
      }
      
      setAgentConfig(prev => ({
        ...config,
        nextGeneration: nextGen.toISOString(),
      }));
    }
    
    toast.success('AI Agent configuration saved!');
  };

  // Simulate automatic daily generation check
  useEffect(() => {
    if (!agentConfig.enabled || !agentConfig.autoGenerateDaily) return;

    const checkInterval = setInterval(() => {
      const now = new Date();
      const [hours, minutes] = agentConfig.generationTime.split(':');
      
      if (
        now.getHours() === parseInt(hours) && 
        now.getMinutes() === parseInt(minutes) &&
        agentConfig.lastGeneration &&
        new Date(agentConfig.lastGeneration).toDateString() !== now.toDateString()
      ) {
        // Trigger automatic generation for all verticals
        const verticals: Vertical[] = ['arts-music', 'fashion-culture', 'sports-leisure', 'business-news'];
        
        toast.info('AI Agent is generating daily stories...');
        
        verticals.forEach(vertical => {
          handleGenerateStories(vertical, agentConfig.storiesPerDay);
        });
      }
    }, 60000); // Check every minute

    return () => clearInterval(checkInterval);
  }, [agentConfig]);

  return (
    <div className="min-h-screen bg-background">
      {/* Admin Login Modal */}
      {showAdminLogin && (
        <div className="fixed inset-0 z-50">
          <AdminLogin onLoginSuccess={handleAdminLoginSuccess} />
        </div>
      )}

      <Header 
        selectedVertical={selectedVertical}
        onVerticalChange={setSelectedVertical}
        onEditorToggle={() => setShowEditor(!showEditor)}
        onAgentToggle={() => setShowAgent(!showAgent)}
        onManualWriteToggle={() => setShowManualForm(!showManualForm)}
        onScheduleToggle={() => setShowSchedule(!showSchedule)}
        showEditor={showEditor}
        onLogoClick={() => setSelectedStory(null)}
        isAdmin={isAdmin}
        onAdminLogout={handleAdminLogout}
      />
      
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Top Leaderboard Ad */}
        <div className="mb-8">
          <FakeAd type="leaderboard" />
        </div>

        {selectedStory ? (
          <StoryDetail 
            story={selectedStory} 
            onBack={() => setSelectedStory(null)}
            onEdit={isAdmin ? () => setShowEditor(true) : undefined}
          />
        ) : (
          <>
            {trendingStories.length > 0 && (
              <TrendingCarousel 
                stories={trendingStories} 
                onStoryClick={setSelectedStory}
              />
            )}
            
            {/* Mid-Banner Ad */}
            <div className="my-8">
              <FakeAd type="banner" />
            </div>

            <div className="mb-6 flex items-center gap-3">
              <div className="h-px flex-1 bg-gradient-to-r from-transparent via-secondary to-transparent"></div>
              <span className="text-sm font-bold uppercase tracking-widest text-muted-foreground">Latest Stories</span>
              <div className="h-px flex-1 bg-gradient-to-r from-secondary via-secondary to-transparent"></div>
            </div>
            <StoryGrid 
              stories={latestStories}
              onStoryClick={setSelectedStory}
            />
            
            {/* Bottom Banner Ad */}
            <div className="mt-8">
              <FakeAd type="banner" />
            </div>
          </>
        )}
      </main>

      {isAdmin && showEditor && selectedStory && (
        <EditorPanel
          story={selectedStory}
          onClose={() => setShowEditor(false)}
          onUpdate={handleStoryUpdate}
        />
      )}

      {isAdmin && showAgent && (
        <AIAgentPanel
          config={agentConfig}
          onClose={() => setShowAgent(false)}
          onUpdateConfig={handleUpdateConfig}
          onGenerateStories={handleGenerateStories}
          isGenerating={isGenerating}
          onGoLive={handleGoLive}
        />
      )}

      {isAdmin && showManualForm && (
        <ManualStoryForm
          onClose={() => setShowManualForm(false)}
          onSave={handleSaveManualStory}
        />
      )}

      {isAdmin && showSchedule && (
        <ScheduleSettings
          onClose={() => setShowSchedule(false)}
        />
      )}

      <Footer />
    </div>
  );
}